version: "3.8"

services:

  db:
    image: karthik26/otp-db:latest
    container_name: otp-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: otpdb
    ports:
      - "5432:5432"

  backend:
    image: karthik26/otp-backend:latest
    container_name: otp-backend
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: otpdb

  frontend:
    image: karthik26/otp-frontend:latest
    container_name: otp-frontend
    restart: always
    ports:
      - "80:80"
